spring.application.name=database

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/activiti-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG



